### ISSUE TITLE
node-red-node-weather-underground crashed node-red

### ISSUE THREAD

**Issue by drJeckyll** [node-red/node-red-web-nodes#158]
node-red-node-weather-underground caused node-red crash:

1 Dec 13:18:47 - SyntaxError: Unexpected token <
    at Object.parse (native)
    at Request._callback (/usr/lib/node_modules/node-red-node-weather-underground/node_modules/wundergroundnode/lib/wundergroundnode.js:137:49)
    at Request.self.callback (/usr/lib/node_modules/node-red-node-weather-underground/node_modules/wundergroundnode/node_modules/request/request.js:186:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/usr/lib/node_modules/node-red-node-weather-underground/node_modules/wundergroundnode/node_modules/request/request.js:1081:10)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/node-red-node-weather-underground/node_modules/wundergroundnode/node_modules/request/request.js:1001:12)
    at IncomingMessage.g (events.js:260:16)

It's happening couple of times last few days.

**Comment by dceejay** [comment]
Hi

That error seems to be coming from the underlying wundergroundnode npm - it calls a JSON.parse on the incoming reply and is obviously tripping up now and again...
I'll try to add a catch for it - but if it is throw asynchronously (which it seems to be) then we will be out of luck.
Updated version pushed to npm

**Comment by drJeckyll** [comment]
There is no crash since then, so I guess it's OK to close issue.

**Comment by knolleary** [comment]
Thanks!
