### ISSUE TITLE
Uncaught exception in latest node-red-node-darksky release

### ISSUE THREAD

**Issue by knolleary** [node-red/node-red-web-nodes#161]
From @Paul-Reed on slack:

After updating darksky to the just released 0.1.13, NR now crashes with:
```
Welcome to Node-RED
===================
13 Dec 23:45:22 - [info] Node-RED version: v0.15.1
13 Dec 23:45:22 - [info] Node.js  version: v4.6.1
13 Dec 23:45:22 - [info] Linux 4.4.26-v7+ arm LE
13 Dec 23:45:24 - [info] Loading palette nodes
pi : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/bin/python -u /usr/lib/node_modules/node-red/nodes/core/hardware/nrgpio.py info
pam_unix(sudo:session): session opened for user root by (uid=0)
pam_unix(sudo:session): session closed for user root
13 Dec 23:45:28 - [info] Dashboard version 2.1.0 started at /home-usage
13 Dec 23:45:35 - [info] Settings file  : /home/pi/.node-red/settings.js
13 Dec 23:45:35 - [info] User directory : /home/pi/.node-red
13 Dec 23:45:35 - [info] Flows file     : /home/pi/.node-red/flows_raspberrypi.json
13 Dec 23:45:36 - [info] Server now running at https://127.0.0.1:8443/admin/
13 Dec 23:45:36 - [info] Starting flows
13 Dec 23:45:38 - [info] Started flows
13 Dec 23:45:38 - [info] [mqtt-broker:ed3cf937.12c308] Connected to broker: mqtt://192.168.1.10:1883
13 Dec 23:45:39 - [red] Uncaught Exception:
13 Dec 23:45:39 - TypeError: Cannot read property 'data' of undefined
at IncomingMessage.<anonymous> (/home/pi/.node-red/node_modules/node-red-node-darksky/darksky.js:95:57)
at emitNone (events.js:72:20)
at IncomingMessage.emit (events.js:166:7)
at endReadableNT (_stream_readable.js:921:12)
at nextTickCallbackWith2Args (node.js:442:9)
at process._tickCallback (node.js:356:17)
nodered.service: main process exited, code=exited, status=1/FAILURE
Unit nodered.service entered failed state.
nodered.service holdoff time over, scheduling restart.
Stopping Node-RED graphical event wiring tool....`
```

Reverting back to darksky 0.1.12 works fine.

**Comment by kuehnelbs** [comment]
Hm - will have a closer look next days. 
Installed 0.1.12 on clean system, updated to 0.1.13. Problem can be reproduced.
In darksky node language is set to en (default) but undefined in request uri.
Quick fix: edit darksky.js.

Find (line 66) 

        //wipe clear the msg properties if they exist, or create it if it doesn't
        msg.payload = {};
        msg.location = {};
        //If there is a value missing, the URL is not initialised.
        if (node.year && node.month && node.day && node.hours && node.minutes) {

insert before:

        // Fallback to default language if undefined
        if (typeof(node.lang == 'undefined')) {
        		node.lang = 'en';
        }

**Comment by dceejay** [comment]
Happy to patch that... publishing as 0.1.14 now
