### ISSUE TITLE
Google Place: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by beneuto** [node-red/node-red-web-nodes#170]
Node-red is frequently (but not always) crashing with the following error when performing a Google Places Nearby lookup.   All parameters are hard coded into the node itself except for Name which is passed in via message.   The name values are simple and do not contain unusual characters.   I have even added preprocessing to strip out non-alphanumeric characters to be sure.

18 Apr 14:55:33 - SyntaxError: Unexpected token < in JSON at position 0
    at Object.parse (native)
    at Request._callback (C:\Users\iccadmin\.node-red\node_modules\node-red-node-google\places.js:254:33)
    at Request.self.callback (C:\Users\iccadmin\.node-red\node_modules\node-red-node-google\node_modules\request\request.js:187:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (C:\Users\iccadmin\.node-red\node_modules\node-red-node-google\node_modules\request\request.js:1044:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (C:\Users\iccadmin\.node-red\node_modules\node-red-node-google\node_modules\request\request.js:965:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by beneuto** [comment]
After some further testing I suspect that the issue may be caused by the payload length exceeding some input limit.   I have isolated a test message that will cause the failure, but if I delete some arbitrary properties it will work (I have done this with different sets of properties at random and it always works).
