### ISSUE TITLE
500 server error causes hard crash

### ISSUE THREAD

**Issue by jtiscione** [node-red/node-red-web-nodes#177]
I've been using this node continuously for several months. Suddenly, several times in the past week node-red has stopped and I've been finding this at the end of the log:

19 May 20:00:10 - [error] [openweathermap:South Salt Lake] 500 Internal error: 500001

This error is uncaught and causes a hard crash that shuts down the entire process.

**Comment by jtiscione** [comment]
This seems to happen if there is an interruption in the network connection- this time it crashed and left this at the end of the log:
9 Jun 22:40:48 - [red] Uncaught Exception:
9 Jun 22:40:48 - Error: socket hang up
    at createHangUpError (_http_client.js:302:15)
    at TLSSocket.socketCloseListener (_http_client.js:334:23)
    at emitOne (events.js:101:20)
    at TLSSocket.emit (events.js:191:7)
    at _handle.close (net.js:511:12)
    at TCP.done [as _onclose] (_tls_wrap.js:332:7)
