### ISSUE TITLE
node-red-node-weather-underground Crashing NR

### ISSUE THREAD

**Issue by nprowler** [node-red/node-red-web-nodes#203]
Seem this node is crashing Node-Red more and more lately.  NR Log.
NR@0.17.5
Nodejs@6.11.3
WU@0.1.10

17 Nov 10:08:02 - [red] Uncaught Exception:
17 Nov 10:08:02 - TypeError: Cannot read property 'hasOwnProperty' of undefined
    at handleResponse (/home/pi/.node-red/node_modules/node-red-node-weather-underground/wunder.js:66:29)
    at Wunderground.<anonymous> (/home/pi/.node-red/node_modules/node-red-node-weather-underground/wunder.js:52:28)
    at Request._callback (/home/pi/.node-red/node_modules/wundergroundnode/lib/wundergroundnode.js:148:22)
    at Request.self.callback (/home/pi/.node-red/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/home/pi/.node-red/node_modules/request/request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/home/pi/.node-red/node_modules/request/request.js:1091:12)

**Comment by dceejay** [comment]
Have pushed a fix to better catch that error... please report if it helps - or reopen if not. Thanks
