### ISSUE TITLE
openweathermap node fails to install on Raspberry Pi

### ISSUE THREAD

**Issue by ir-fuel** [node-red/node-red-web-nodes#245]
This is what I get:

```
pi@nodered:~/.node-red $ npm install node-red-node-openweathermap
npm WARN deprecated hawk@6.0.2: This module moved to @hapi/hawk. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
npm WARN deprecated cryptiles@3.1.4: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated hoek@4.2.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated boom@4.3.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated sntp@2.1.0: This module moved to @hapi/sntp. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
npm WARN deprecated boom@5.2.0: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).

> bcrypt@1.0.3 install /home/pi/.node-red/node_modules/node-red/node_modules/bcrypt
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(404): https://github.com/kelektiv/node.bcrypt.js/releases/download/v1.0.3/bcrypt_lib-v1.0.3-node-v64-linux-arm.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for bcrypt@1.0.3 and node@10.15.0 (node-v64 ABI) (falling back to source compile with node-gyp)
node-pre-gyp ERR! Tried to download(undefined): https://github.com/kelektiv/node.bcrypt.js/releases/download/v1.0.3/bcrypt_lib-v1.0.3-node-v64-linux-arm.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for bcrypt@1.0.3 and node@10.15.0 (node-v64 ABI) (falling back to source compile with node-gyp)
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module '../'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js:8:13)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js clean' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/pi/.node-red/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
node-pre-gyp ERR! System Linux 4.14.79-v7+
node-pre-gyp ERR! command "/usr/bin/node" "/home/pi/.node-red/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/pi/.node-red/node_modules/node-red/node_modules/bcrypt
node-pre-gyp ERR! node -v v10.15.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.36
node-pre-gyp ERR! not ok
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module '../'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js:8:13)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js clean' (1)
npm WARN marked-terminal@1.7.0 requires a peer of marked@^0.3.3 but none is installed. You must install peer dependencies yourself.
npm WARN node-red-project@0.0.1 No repository field.
npm WARN node-red-project@0.0.1 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: bcrypt@1.0.3 (node_modules/node-red/node_modules/bcrypt):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: bcrypt@1.0.3 install: `node-pre-gyp install --fallback-to-build`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

+ node-red-node-openweathermap@0.2.1
added 20 packages from 16 contributors and audited 2653 packages in 31.563s
found 24 vulnerabilities (1 low, 8 moderate, 15 high)
  run `npm audit fix` to fix them, or `npm audit` for details
```

Seems to be a problem with bcrypt. A too old version combined with a too recent version of Node.

**Comment by dceejay** [comment]
this doesn't seem to be a problem with openweathermap - that seemed to install ok.

**Comment by ir-fuel** [comment]
Well maybe some dependencies need updating?
BTW I always have issues with stuff depending (indirectly) on old bcrypt versions

**Comment by dceejay** [comment]
that is in the core - maybe retry with 
 `npm i --unsafe-perm node-red-node-openweathermap`

**Comment by ir-fuel** [comment]
I don't see how that option will change anything (it has to do with permissions if I recall correctly), but I just noticed in the logs that bcrypt is marked as an optional dependency at the end of the install, so maybe it works.

**Comment by dceejay** [comment]
Which version of Node-RED are you on ?
The bcrypt thing should go away as and when you upgrade using the upgrade script.
The perms flag stops node-gyp (which calls the compile) from dropping privileges (nobody user) which may allow it to find, read and write the files it needs, or may not.

**Comment by ir-fuel** [comment]
latest version. I updated a couple of hours ago. 0.20.8

**Comment by ir-fuel** [comment]
The error is exactly the same btw, using `unsafe-perm`

**Comment by ir-fuel** [comment]
What's even stranger is that this:

http://npm.anvaka.com/#/view/2d/node-red-node-openweathermap

Does not even show `bcrypt` as a dependency

**Comment by dceejay** [comment]
it's nothing to do with openweathermap. 
It's just when npm runs it tries to re-flatten/optimise all dependencies - and as it hasn't yet build that one it tries to redo it. You could try
```
cd /usr/lib/node_modules/node-red
sudo npm i -g --unsafe-perm
```
which should re-install the core

**Comment by ir-fuel** [comment]
It was a case of "throw everything away and restart"

I inspected the `package-lock.json` file in my `.node-red` folder and found a `bcrypt 1.0.3` dependency underneath a `node-red 0.18.0` dependency, which makes no sense as that node-red version was upgraded.

I deleted the lock file, deleted `node_modules`, reinstalled the node-red upgrade and now it's working.
